# Generated by Django 5.2.1 on 2025-06-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargest', '0002_alter_car_latitude_alter_car_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Valor entre -90 y 90', null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='car',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Valor entre -180 y 180', null=True, verbose_name='Longitud'),
        ),
    ]
