# Generated by Django 5.2.1 on 2025-06-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargest', '0002_alter_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
